REM INSERTING into DRAPAT_APLIKASI
Insert into DRAPAT_APLIKASI (ID_RAPAT,ID_APLIKASI,STATE_RA) values ('RPT-002','APP02','1');
Insert into DRAPAT_APLIKASI (ID_RAPAT,ID_APLIKASI,STATE_RA) values ('RPT-002','APP03','1');
Insert into DRAPAT_APLIKASI (ID_RAPAT,ID_APLIKASI,STATE_RA) values ('RPT-003','APP04','1');
Insert into DRAPAT_APLIKASI (ID_RAPAT,ID_APLIKASI,STATE_RA) values ('RPT-009','APP02','1');
Insert into DRAPAT_APLIKASI (ID_RAPAT,ID_APLIKASI,STATE_RA) values ('RPT-009','APP05','1');
