REM INSERTING into RAPAT_USER
Insert into RAPAT_USER (ID_USER,ID_RAPAT,REMINDER,PRIORITAS,CATATAN,STATE_RU) values ('USR04','RPT-008',null,null,null,'1');
Insert into RAPAT_USER (ID_USER,ID_RAPAT,REMINDER,PRIORITAS,CATATAN,STATE_RU) values ('USR01','RPT-003',null,null,null,'1');
Insert into RAPAT_USER (ID_USER,ID_RAPAT,REMINDER,PRIORITAS,CATATAN,STATE_RU) values ('USR02','RPT-003',null,null,null,'1');
Insert into RAPAT_USER (ID_USER,ID_RAPAT,REMINDER,PRIORITAS,CATATAN,STATE_RU) values ('USR04','RPT-009',null,null,null,'1');
